apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: prod # 替换为你的实际命名空间
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec: 
      containers:
      - name: api-gateway
        #  动态替换 tag
        image: gravitex-ap-southeast-1.cr.bytepluses.com/gravitex/api-gateway:1.0.2
        ports:
        - containerPort: 3000
